name: bigquery_assessment
version: "1.0"
extract_folder: "~/.databricks/labs/lakebridge_profilers/bigquery_assessment"
steps:
  - name: bq_metadata_extract
    type: python
    extract_source: src/databricks/labs/lakebridge/resources/assessments/bigquery/bq_metadata_extract.py
    mode: overwrite
    frequency: once
    flag: active
    dependencies:
      - pandas
      - duckdb
      - pyyaml
      - google-cloud-bigquery>=3.0.0
      - google-cloud-bigquery-storage>=2.0.0
      - google-auth>=2.0.0
      - db-dtypes>=1.0.0
      - databricks-sdk
      - databricks-labs-blueprint[yaml]>=0.10.1
